apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-test
    app.kubernetes.io/part-of: fbc-app
  name: fbc-component
  namespace: managed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fbc-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fbc-component
    spec:
      containers:
      - image: quay.io/lmendes/user-workload@sha256:d50a2b9e57a8366ae99bf89c03a8169807befd0ddc94f026254f90d6814af5d3
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
